import "./globals.css"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AppGlobalProviders } from "./components/globalProviders"
import { cookies } from 'next/headers'

/*
	use 
	https://nextui.org/docs/guide/installation
*/ 

const inter = Inter({ subsets: ['latin'] })

interface RootLayoutProps {
	children: React.ReactNode
	auth: React.ReactNode
}

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout(
	props: RootLayoutProps
) {
	const cookieStore = cookies();
	const token = cookieStore.get('token');
	return (
		<html lang="en" className={"fixed inset-0 flex items-center justify-center"}>
					<body>
					<AppGlobalProviders>
						<main className={inter.className}>
							{token ? props.children : props.auth}
						</main>
					</AppGlobalProviders>
					</body>
		</html>
	);
}
